const typeOfProject = ['Home', 'Plots', 'Commercial', 'Industrial']
const home = ['Home', 'Flats', 'Lower Portion', 'Upper Portion', 'Farm House', 'Room', 'Other']
const plots = [
  'Agriculture Plot',
  'Commercial Plot',
  'Residential Plot',
  'Plot File',
  'Industrial Land',
  'Other',
]
const commercial = ['Office', 'Shop', 'WareHouse', 'Factory', 'Building', 'Other']
const stage = [
  'Planning',
  'Ground',
  'Infrastructure',
  'Under-Construction',
  'Under-Developed',
  'Developed',
  'Renovation',
]
const flooring = ['Tile', 'Marble', 'Wooden', 'Chip', 'Cement', 'Other']
const electricityBackup = ['N/A', 'Generator', 'UPS', 'Solar', 'Main Line', 'Other']
const powerSupply = ['1 Phase', '2 Phase', '3 Phase', 'N/A']
const pakistaniCities = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Sialkot',
  'Gujranwala',
  'Hyderabad',
  'Sukkur',
  'Bahawalpur',
  'Sargodha',
  'Rahim Yar Khan',
  'Jhang',
  'Sheikhupura',
  'Larkana',
  'Gujrat',
  'Mardan',
  'Kasur',
  'Dera Ghazi Khan',
  'Sahiwal',
  'Okara',
  'Wah Cantt',
  'Mingora',
  'Mirpur Khas',
  'Chiniot',
  'Kamoke',
  'Mandi Bahauddin',
  'Nawabshah',
  'Kohat',
  'Dera Ismail Khan',
  'Abbottabad',
  'Turbat',
  'Bannu',
  'Bhakkar',
  'Jhelum',
  'Khanewal',
  'Hafizabad',
  'Shikarpur',
  'Muzaffargarh',
  'Khanpur',
  'Gojra',
  'Bahawalnagar',
  'Muridke',
  'Pakpattan',
  'Tando Adam',
  'Khairpur',
  'Jacobabad',
  'Jaranwala',
  'Chishtian',
  'Daska',
  'Mandi',
  'Tando Allahyar',
  'Dadu',
  'Vehari',
  'Nowshera',
  'Khuzdar',
  'Swabi',
  'Charsadda',
]


export {
  typeOfProject,
  home,
    plots,
    commercial,
    stage,
    flooring,
    electricityBackup,
    powerSupply,
    pakistaniCities,
}